language: minimal

services:
  - docker

jobs:
  include:
    - stage: build deb
      if: tag IS present
      before_install:
      - docker pull woodenfish42/hustoj-deb-debian8
      - docker pull woodenfish42/hustoj-deb-ubuntu18
      script:
      - docker run -v `pwd`/deb:/tmp/deb woodenfish42/hustoj-deb-debian8 sh -c "TRAVIS_TAG=$TRAVIS_TAG DISTRIBUTION=debian8 /root/build.sh"
      - docker run -v `pwd`/deb:/tmp/deb woodenfish42/hustoj-deb-ubuntu18 sh -c "TRAVIS_TAG=$TRAVIS_TAG DISTRIBUTION=ubuntu18 /root/build.sh"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: deb/*
        skip_cleanup: true
        on:
          tags: true
    - stage: sync to gitee
      if: branch = master
      script:
      - git fetch --unshallow
      - git gc --prune=now
      - travis_wait 30 git push --force https://zhblue:$GITEE_PASSWORD@gitee.com/zhblue/hustoj.git master
